export type ColorNames =
  | 'transparent'
  | 'current'
  | 'white'
  | 'black'
  | 'red'
  | 'light-red'
  | 'light-gray'
  | 'gray'
  | 'dark-gray'
  | 'green'
  | 'light-blue'
  | 'blue'
  | 'dark-blue'
  | 'yellow'
  | 'dark-yellow';
